image:
  repository: nginx
  tag: latest
  pullPolicy: Always

service:
  port: 80

global:
  replicas: 1

ingress:
  enabled: true
  host: your-app.local
  path: /
  className: nginx

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

config:
  enabled: true
  data:
    APP_ENV: production
    LOG_LEVEL: info

externalSecret:
  enabled: true
  name: app-secrets
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: kv/data/app
        property: db_password
